{
    "name": "Comparación con ARCA de facturas recibidas",
    "version": "19.0.1.1.10",
    "summary": "Compara la exportación 'Mis Comprobantes Recibidos' de ARCA con las facturas de proveedores de Odoo",
    "author": "Zinapsia",
    "website": "https://www.zinapsia.com",
    "license": "AGPL-3",
    "category": "Accounting/Localizations",
    "depends": [
        "account",
        "l10n_ar",
        "documents",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "views/arca_bill_comparison_line_views.xml",
        "views/arca_bill_comparison_batch_views.xml",
        "wizards/arca_bill_comparison_wizard_views.xml",
        "views/menu_items.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
